spring.application.name=stocksurge-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/stocksurge
spring.datasource.username=postgres
spring.datasource.password=Aryan@post7
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
